name: e2e
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.3.0=h27087fc_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.2.1.32=h86fa8c9_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=5.0.1=h964e5f1_2
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.44=h153f514_2
  - libdrm=2.4.124=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnsl=2.0.0=h5eee18b_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.18=hd6dcaed_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310hcf8288c_1
  - readline=8.3=hc2a1206_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=1.1.0=h27087fc_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==1.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-record==0.8.1
      - arrow==1.4.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - cachetools==5.5.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dacite==1.8.1
      - dask==2023.3.1
      - dataclass-array==1.5.1
      - defusedxml==0.7.1
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - einsum==0.3.0
      - etils==1.13.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2025.9.0
      - gast==0.4.0
      - gcsfs==2025.10.0
      - google-api-core==2.28.1
      - google-auth==2.16.2
      - google-auth-oauthlib==1.0.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==2.11.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - grpcio==1.74.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - immutabledict==2.2.0
      - importlib-resources==6.4.5
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-http-over-ws==0.0.8
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==2.13.1
      - kiwisolver==1.4.7
      - lark==1.3.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.8
      - locket==1.0.0
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - partd==1.4.2
      - pillow==11.3.0
      - pip==25.3
      - plotly==5.13.1
      - prometheus-client==0.23.1
      - promise==2.3
      - propcache==0.2.0
      - proto-plus==1.26.1
      - protobuf==4.21.12
      - psutil==6.1.0
      - pyarrow==16.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pyg-lib==0.4.0+pt28cu128
      - pyparsing==3.2.0
      - python-json-logger==4.0.0
      - pytorch-lightning==2.0.3
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - setuptools==70.2.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - simple-parsing==0.1.7
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-datasets==4.9.9
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - tensorflow-probability==0.21.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.8.0+cu128
      - torch-cluster==1.6.3+pt28cu128
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt28cu128
      - torch-sparse==0.6.18+pt28cu128
      - torch-spline-conv==1.2.2+pt28cu128
      - torchaudio==2.8.0+cu128
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - visu3d==1.5.1
      - waymo-open-dataset-tf-2-12-0==1.6.7
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.18.3
prefix: /home/hansung/miniconda3/envs/e2e
